### ISSUE TITLE
Add Video upload and stt api 

### ISSUE THREAD

**Issue by FacerAin** [KHUMON-EDU/khumon-simple-demo#2]
## 🚀 Feature Request
**Why**
- 사용자가 비디오를 업로드하면 음성을 추출하여 stt api를 통해 텍스트로 변환 필요
- 적당하게 음성에 배속을 걸면 api 호출을 아낄 수 있지 않을까?

**Todo**
- [x] 비디오 업로드 추가
- [x] 업로드 한 비디오에서 음성 추출
- [x] 추출한 음성을 stt api를 통해 텍스트로 변환(취소) -> Whisper로 변환

## 📎 Additional context
- OPENAI [Whisper](https://github.com/openai/whisper)도 고려해보기
